#!/bin/sh
HOST=localhost
PORT=1234
FILE1=/tmp/main1-$$
FILE2=/tmp/main2-$$
ERROR=/tmp/main-err-$$
MAIN=main
GETTEXT="gettext -d main_ui"
DMSG="`$GETTEXT \"Please, choose the channel:\"`\n`$GETTEXT \"1 - Regularly encrypted channel\"`\n`$GETTEXT \"2 - Quantum encrypted channel\"`\n"
WRNG="`$GETTEXT \"Incorrect value. Please, try again\"`"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

if [ $# -ge 1 -o `basename $0` = 'nmain_ui' ]
then
	if [ $HOST -a $PORT ]
	then
	        MAIN="nc $HOST $PORT"
	else
		echo "Please, set HOST and PORT first"
		exit -2
	fi
fi


end () {
    rm -f $FILE1 $FILE2 $ERROR
    exit
}

switchSignal () {
    echo $1
    if echo $1 | $MAIN 1> $FILE2 2> $ERROR
    then 
      if grep -qF "Switched" $FILE2
      then
        case $1 in
        1) chan="`$GETTEXT \"with regular encryption\"`";;
        2) chan="`$GETTEXT \"with quantum encryption\"`";;
        esac
        message="`$GETTEXT \"Successfully switched to the channel \"``$GETTEXT \"$chan\"`\n\n`$GETTEXT \"Continue?\"`"
      else 
       message="`$GETTEXT \"Response from the server:\"`\n`cat $FILE2`\n\n`$GETTEXT \"Continue?\"`" 
      fi
    else 
      message="`$GETTEXT \"Error:\"`\n`cat $ERROR`\n\n`$GETTEXT \"Continue?\"`"
    fi
    $DIALOG --title "$title" --yesno "$message" 10 35
    response=$?
    case $response in
      0) showDialog;;
      1) end;;
    esac
}

checkValue () {
    if [ "$1" != "1" ] && [ "$1" != "2" ]
    then 
      showDialog $1
    else
      switchSignal $1  
    fi   
}

showDialog () {
    if [ $# -eq 0 ]
    then
      MSG="$DMSG"
    else 
      MSG="$DMSG $WRNG"
    fi
    $DIALOG --inputbox "$MSG" 10 40 2> $FILE1 || end
    value=`cat $FILE1`
    checkValue $value
}

showDialog

