#!/bin/sh

FILE1=/tmp/calc1-$$
FILE2=/tmp/calc2-$$
ERROR=/tmp/calc-err-$$
MAIN=./main
MSG="Please, choose the channel\n1 - Regularly encrypted channel\n2 - Quantum encrypted channel"

which gdialog 2> /dev/null && DIALOG=gdialog || DIALOG=dialog

end () {
    rm -f $FILE1 $FILE2 $ERROR
    exit
}

switchSignal () {
    echo "value in switchSignal: $1"
    $MAIN $1
    $DIALOG --title 'Success' --msgbox "Succesfully switched to channel $1" 5 30
    end
}

checkValue () {
    echo "value in checkValue: $1"
    if [ "$1" != "1" ] && [ "$1" != "2" ]
    then 
      showDialog
    else
      switchSignal $1  
    fi   
}

showDialog () {
    $DIALOG --inputbox "$MSG" 10 40 2> $FILE1 || end
    value=`cat $FILE1`
    checkValue $value
}

showDialog




